// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduller.Api.Infrasturctures;

#nullable disable

namespace Scheduller.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112023554_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("models");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.ProcessComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseQuantity")
                        .HasColumnType("int")
                        .HasColumnName("base_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CycleTime")
                        .HasColumnType("int")
                        .HasColumnName("cycle_time");

                    b.Property<int>("OperationNumber")
                        .HasColumnType("int")
                        .HasColumnName("operation_number");

                    b.Property<int>("PartsId")
                        .HasColumnType("int")
                        .HasColumnName("parts_id");

                    b.Property<int>("Setup")
                        .HasColumnType("int")
                        .HasColumnName("setup");

                    b.Property<int>("WorkCenterCategory")
                        .HasColumnType("int")
                        .HasColumnName("work_center_category");

                    b.Property<int>("WorkCentersId")
                        .HasColumnType("int")
                        .HasColumnName("work_centers_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkCentersId");

                    b.HasIndex("PartsId", "OperationNumber");

                    b.ToTable("process_components");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.ProcessDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bom")
                        .HasColumnType("int")
                        .HasColumnName("bom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("ModelsId")
                        .HasColumnType("int")
                        .HasColumnName("models_id");

                    b.Property<int>("OperationNumber")
                        .HasColumnType("int")
                        .HasColumnName("operation_number");

                    b.Property<int>("PartsId")
                        .HasColumnType("int")
                        .HasColumnName("parts_id");

                    b.HasKey("Id");

                    b.HasIndex("PartsId");

                    b.HasIndex("ModelsId", "PartsId", "OperationNumber");

                    b.ToTable("process_details");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("work_centers");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.ProcessComponent", b =>
                {
                    b.HasOne("Scheduller.Api.Domains.Entities.Part", "Part")
                        .WithMany("ProcessComponents")
                        .HasForeignKey("PartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scheduller.Api.Domains.Entities.WorkCenter", "WorkCenter")
                        .WithMany("ProcessComponents")
                        .HasForeignKey("WorkCentersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.ProcessDetail", b =>
                {
                    b.HasOne("Scheduller.Api.Domains.Entities.Model", "Model")
                        .WithMany("ProcessDetails")
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scheduller.Api.Domains.Entities.Part", "Part")
                        .WithMany("ProcessDetails")
                        .HasForeignKey("PartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.Model", b =>
                {
                    b.Navigation("ProcessDetails");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.Part", b =>
                {
                    b.Navigation("ProcessComponents");

                    b.Navigation("ProcessDetails");
                });

            modelBuilder.Entity("Scheduller.Api.Domains.Entities.WorkCenter", b =>
                {
                    b.Navigation("ProcessComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
